docker-build:
	docker build -t southamerica-east1-docker.pkg.dev/midia-in-da-house/gke-cr/bff-storage:latest .

docker-push:
	docker push southamerica-east1-docker.pkg.dev/midia-in-da-house/gke-cr/bff-storage:latest