stages:
  - test
  - build
  - deploy
  # more stages

include:
  - local: ".gitlab/ci/variables.yml"
  - local: ".gitlab/ci/actions-rules.yml"
  - local: ".gitlab/ci/branch-rules.yml"
  - local: ".gitlab/ci/pipeline-check.yml"
  - local: ".gitlab/ci/docs.yml"
  - local: ".gitlab/ci/release.yml"
  - local: ".gitlab/ci/frontend.yml"
  - local: ".gitlab/ci/go.yml"
  - local: ".gitlab/ci/rust.yml"
  - local: ".gitlab/ci/python.yml"
  - local: ".gitlab/ci/iac.yml"
  # more component pipelines
