apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-writer-cm
data:
  KAFKA_BROKERS: "my-cluster-kafka-bootstrap.kafka.svc:9092"
  KAFKA_TOPIC: "geodata"
  KAFKA_GROUP_ID: "go-consumer-group"
  KAFKA_MIN_BYTES: "1000"
  KAFKA_MAX_BYTES: "10000000"
  KAFKA_READ_TIMEOUT: "5s"
  KAFKA_MAX_WAIT: "500ms"
  PROCESS_DELAY: "0"


