apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-writer
  name: redis-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-writer
  strategy: {}
  template:
    metadata:
      labels:
        app: redis-writer
    spec:
      containers:
      - image: redis-writer:2.0
        name: redis-writer
        envFrom:
          - configMapRef:
              name: redis-writer-cm
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
