apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-cm
data:
  LLM_PROVIDER: "groq"
  LLM_MODEL: "llama-3.3-70b-versatile"
  LLM_TEMPERATURE: "0.3"
  GEOCODING_PROVIDER: "nominatim"
  BQ_PROJECT_ID: "midia-in-da-house"
  BQ_DATASET_ID: "eletromidia_bq"
  BQ_SA_CREDENTIALS: "/secrets/bq-sa-key.json"
  LOOKER_REPORT_ID: "1776f716-b7de-4268-99ef-8107f950868d"
  LOOKER_PAGE_ID: "p_dmgnzqj61d"
  LOOKER_DS_ALIAS: "ds0"
  PYTHONDONTWRITEBYTECODE: "1"
  CORS_ORIGINS: "https://midia-in-da-house.web.app"
