apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-middleware-cm
data:
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "5000"
  FIREBASE_PROJECT_ID: "midia-in-da-house"
  GCP_PROJECT_ID: "midia-in-da-house"
  # Default development roles
  ROLE_ADMIN: "roles/resourcemanager.projectIamAdmin"
  ROLE_EDITOR: "roles/looker.developer"
  ROLE_VIEWER: "roles/looker.accessUser"
  ROLE_MANAGER: "roles/owner"
  GOOGLE_APPLICATION_CREDENTIALS: "/secrets/gcp-sa-key.json"
