docker-build:
	docker build -t southamerica-east1-docker.pkg.dev/midia-in-da-house/gke-cr/rust-producer:latest services/csv-kafka-producer

docker-push:
	docker push southamerica-east1-docker.pkg.dev/midia-in-da-house/gke-cr/rust-producer:latest