apiVersion: v1
kind: ConfigMap
metadata:
  name: rust-producer-cm
data:
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.kafka.svc:9092"
  KAFKA_TOPIC: "geodata-dev"
  KAFKA_RECORD_KEY: csv-row
  KAFKA_MESSAGE_TIMEOUT_MS: "5000"
  KAFKA_COMPRESSION_TYPE: zstd
  KAFKA_BATCH_SIZE: "1048576"
  KAFKA_LINGER_MS: "0"
  KAFKA_QUEUE_BUFFERING_MAX_MESSAGES: "100000"
  KAFKA_ACKS: "1"
  KAFKA_REQUEST_TIMEOUT_MS: "30000"
  KAFKA_PARTITIONER: "murmur2_random"

  # CSV
  CSV_FILEPATH: /app/data/dados_geodata.csv
  CSV_RELOAD_INTERVAL_SECS: "86400"

  # HTTP Server
  HTTP_HOST: 0.0.0.0
  HTTP_PORT: "5000"

  # Load Test (defaults para API)
  LOAD_TEST_BATCH_SIZE: "500"
  LOAD_TEST_DEFAULT_RATE: "100000"
  LOAD_TEST_AUTO_TAXA_INICIAL_MIN: "100000"
  LOAD_TEST_AUTO_TAXA_MAX_LIMITE: '5000000'
  LOAD_TEST_AUTO_ERRO_THRESHOLD: "0.01"
  LOAD_TEST_AUTO_TAXA_MIN_REDUCAO: "1000"
  LOAD_TEST_AUTO_FATOR_AUMENTO: "2.0"
  LOAD_TEST_AUTO_FATOR_REDUCAO: "0.7"

