apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rust-producer
    kafka-role: producer
  name: rust-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-producer
      kafka-role: producer
  strategy: {}
  template:
    metadata:
      labels:
        app: rust-producer
        kafka-role: producer
    spec:
      securityContext:
        runAsUser: 1010
        runAsNonRoot: true
      automountServiceAccountToken: false
      containers:
      - image: southamerica-east1-docker.pkg.dev/midia-in-da-house/gke-cr/rust-producer:latest
        imagePullPolicy: Always
        name: rust-producer
        ports:
          - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
          # readOnlyRootFilesystem: true
        envFrom:
          - configMapRef:
              name: rust-producer-cm
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"