apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-storage-cm
data:
  PROJECT_ID: "midia-in-da-house"
  BUCKET_NAME: "kafka-backup-eletromidia"
  CS_SA_CREDENTIALS: "/secrets/cs-api-key.json"
  BQ_PROJECT_ID: "midia-in-da-house"
  BQ_DATASET_ID: "eletromidia_bq_dev"
  BQ_SA_CREDENTIALS: "/secrets/cs-api-key.json"
