# Como o BFF-Storage não é um serviço interno, ele preciso se expor
# Criei um NodePort somente para teste
# Futuramente criarei um API Gateway

apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-storage-svc
  name: bff-storage-svc
spec:
  ports:
  - name: 5678-8080
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: bff-storage
  type: NodePort
status:
  loadBalancer: {}
